apiVersion: apps/v1beta1
kind: deployment
metadata:
  name: mern-app-deployment
  labels:
    app: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
        - name: frontend
          image: priyanshcchoudhary/expensetracker-main-frontend:latest
          ports:
            - containerPort: 3000
        - name: backend
          image: priyanshcchoudhary/expensetracker-main-backend:latest
          ports:
            - containerPort: 5000
