apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: mern-app-pod
  ports:
    - protocol: TCP
      port: 30300
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: mern-app-pod
  ports:
    - protocol: TCP
      port: 30500
      targetPort: 5000
